Tarea1/Models/CategoriaProductos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tarea1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaProductos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CategoriaProductos()
        {
            this.Producto = new HashSet<Producto>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto> Producto { get; set; }
    }
}

Tarea1/Controllers/CategoriaProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tarea1.Models;

namespace Tarea1.Controllers
{
    public class CategoriaProductosController : Controller
    {
        Models.Tarea1Entities2 contexto = new Models.Tarea1Entities2();
        // GET: Productos
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Validar()
        {
            //Capturar los  valores del formulario
            var email = Request["email"];
            var pass = Request["password"];
            //Buscar los datos en la BD
            var usu = (from u in contexto.Usuario where u.email == email && u.pass == pass select u).FirstOrDefault();
            //Si existen Crear session con los datos
            if(usu!=null)
            {
                Session["Usuario"] = usu;
                 return RedirectToAction("Listar");
            }
            else
            {
                return RedirectToAction("Index");
            }
            //Si no redirecciono al Index con un mensaje
        }

        public ActionResult Listar()
        {
            if(Session["Usuario"]!=null)
            {
                var cat = contexto.CategoriaProductos.ToList();
                ViewBag.Categorias = cat;
                return View(cat);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult Eliminar(int id)
        {
            if (Session["Usuario"] != null)
            {
                var cat = (from p in contexto.CategoriaProductos where p.Id == id select p).FirstOrDefault();

                contexto.CategoriaProductos.Remove(cat);

                contexto.SaveChanges();

                return RedirectToAction("Listar");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult Guardar()
        {
            string mensaje = "";
            var id = Request["idCategoriaProductos"];
            var nombre = Request["nombre"];


            CategoriaProductos c = new CategoriaProductos();
            c.Id = int.Parse(id);
            c.Nombre = nombre;

            
            try
            {
                contexto.CategoriaProductos.Add(c);
                contexto.SaveChanges();
                mensaje = "Guardado con exito";
            }
            catch(Exception ex)
            {
                mensaje = "Error al guardar el dato";
            }
            ViewBag.mensaje = mensaje;

            return RedirectToAction("Listar");
        }

        public ActionResult MostrarModificar(int id)
        {
            var cat = (from p in contexto.CategoriaProductos where p.Id == id select p).FirstOrDefault();


            if (cat != null)
            {
                var cate = contexto.CategoriaProductos.ToList();
                ViewBag.Categorias = cate;
                return View(cat);
            }
            else
                return RedirectToAction("Listar");
        }

        public ActionResult GuardarModificar()
        {
            int id = int.Parse(Request["idCategoriaProductos"]);
            var nombre = Request["nombre"];


            CategoriaProductos c = (from pro in contexto.CategoriaProductos where pro.Id == id select pro).FirstOrDefault();
            if(c!=null)
            {
                c.Nombre = nombre;

                contexto.SaveChanges();
            }
            
            return RedirectToAction("Listar");
        }
    }
}

Tarea1/Views/CategoriaProductos/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Login Usuario para Ver CategoriaProductos </h2>
<div class="row">
    <div class="col-lg-4">
        <form action="@Url.Action("Validar", "CategoriaProductos")" method="post">
            <div class="form-group">
                <label for="email">Email</label>
                <input type="email" name="email" class="form-control" />
            </div>
            <div class="form-group">
                <label for="password">Password</label>
                <input type="password" name="password" class="form-control" />
            </div>

            <input type="submit" value="Ingresar" class="btn btn-primary" />
        </form>
    </div>
</div>

Tarea1/Views/CategoriaProductos/Listar.cshtml
@model IEnumerable<Tarea1.Models.CategoriaProductos>

@{
    ViewBag.Title = "Listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Listar Categorias</h2>

<div class="row">
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
        Agregar
    </button>

</div>
<br />
<div class="row">
    <div class="col-lg-12">
        <table class="table table-bordered table-striped">
            <tr>
                <th>ID</th>
                <th>Nombre</th>
                <th colspan="2">Acciones</th>
            </tr>
            @foreach (var cate in Model)
            {
                <tr>
                    <td>@cate.Id</td>
                    <td>@cate.Nombre</td>
                    <td>@Html.ActionLink("Eliminar", "Eliminar/" + cate.Id, "CategoriaProductos")</td>
                    <td>@Html.ActionLink("Modificar", "MostrarModificar/" + cate.Id, "CategoriaProductos")</td>
                </tr>
            }
        </table>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <form method="post" action="@Url.Action("Guardar", "CategoriaProductos")">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLongTitle">Nuevo CategoriaProductos</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <div class="form-group">
                        <label for="idCategoriaProductos">ID CategoriaProductos</label>
                        <input type="number" name="idCategoriaProductos" class="form-control" />
                    </div>
                    <div class="form-group">
                        <label for="nombre">Nombre</label>
                        <input type="text" name="nombre" class="form-control" />
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                    <input type="submit" class="btn btn-primary" value="Guardar" />
                </div>
            </div>
        </form>
    </div>
</div>

Tarea1/Views/CategoriaProductos/MostrarModificar.cshtml
@model Tarea1.Models.CategoriaProductos

@{
    ViewBag.Title = "MostrarModificar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2> Modificar CategoriaProductos</h2>

<div class="row">
    <div class="col-lg-6">
        <form method="post" action="@Url.Action("GuardarModificar", "CategoriaProductos")">


            <div class="form-group">
                <label for="idCategoriaProductos">ID CategoriaProductos</label>
                <input type="number" name="idCategoriaProductos" class="form-control" value="@Model.Id" readonly />
            </div>
            <div class="form-group">
                <label for="nombre">Nombre</label>
                <input type="text" name="nombre" class="form-control" value="@Model.Nombre" />
            </div>

            <input type="submit" value="Guardar" class="btn btn-primary" />
        </form>

    </div>
</div>